version: 2.1
jobs:
  build:
    docker:
      - image: tiltdev/tilt:latest

    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.12
      - run: |
          apt install curl gnupg &&
          curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor > bazel.gpg &&
          mv bazel.gpg /etc/apt/trusted.gpg.d/ &&
          echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | tee /etc/apt/sources.list.d/bazel.list
      - run: apt update && apt install -y git bazel golang python3 python3-pip python-pip
      - run: ctlptl create cluster kind --registry=ctlptl-registry && test/test.sh
